<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15" started-at="2014-07-28T13:10:01Z" finished-at="2014-07-28T13:10:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15" started-at="2014-07-28T13:10:01Z" finished-at="2014-07-28T13:10:01Z">
      <class name="com.EriBank.TestEriBankIOs">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:com.EriBank.TestEriBankIOs@880ec60]" name="setUp" is-config="true" duration-ms="0" started-at="2014-07-28T18:40:01Z" finished-at="2014-07-28T18:40:01Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at aiframework.core.utils.TestShell.startProcess(TestShell.java:74)
	at aiframework.core.utils.TestBase.startAppiumServer(TestBase.java:200)
	at com.EriBank.TestEriBankIOs.setUp(TestEriBankIOs.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:277)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testCaseOne()[pri:0, instance:com.EriBank.TestEriBankIOs@880ec60]" name="testCaseOne" duration-ms="1" started-at="2014-07-28T18:40:01Z" finished-at="2014-07-28T18:40:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseOne -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.EriBank.TestEriBankIOs@880ec60]" name="tearDown" is-config="true" duration-ms="0" started-at="2014-07-28T18:40:01Z" finished-at="2014-07-28T18:40:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.EriBank.TestEriBankIOs -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
